{
 "title": "Monitoring Ordinateur",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(cpu_percent) AS \"CPU %\"\nFROM cpu_usage\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "gauge",
   "description": "Disk C",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(percent) AS \"percent\"\nFROM disk_usage_c\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(percent) AS \"percent\"\nFROM disk_usage_d\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(bytes_recv) AS \"bytes_recv\"\nFROM net_io_counter\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(bytes_sent) AS \"bytes_recv\"\nFROM net_io_counter\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(packets_recv) AS \"packets_recv\"\nFROM net_io_counter\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(packets_sent) AS \"packets_sent\"\nFROM net_io_counter\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  avg(percent) AS \"available\"\nFROM memory\nWHERE\n  $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  }
 ]
}